                    print("\t\t\t#######################################################")
                    print("\t\t\t#<--You are doing Automation on your local computer-->#")
                    print("\t\t\t#######################################################")
                    print("\t\t\t#------------You are in Partition(LVM) Opt----------->#")
                    print("\t\t\t#######################################################")
                    print("\t\t\t# Press 1 : To list the hard disk available in pc     #")
                    print("\t\t\t# Press 2 : To create new drive                       #")
                    print("\t\t\t# Press 3 : To extend existing drive                  #")
                    print("\t\t\t# Press 4 : To attach new hard disk to the drive      #")
                    print("\t\t\t# Press 5 : To see all the mounted folder             #")
                    print("\t\t\t# Press 6 : To exit                                   #")
                    print("\t\t\t#######################################################")
                    lvm = input("Enter Your Choice: ")
                    if int(lvm) == 1:
                        os.system('fdisk  -l')
                    elif int(lvm) == 2:
                        disk = input("Enter the newly attached hard disk full name eg - /dev/sda: ")
                        os.system('pvcreate ()'.format(disk))
                        print("PV created successfully")
                        folder = input("enter the folder name: ")
                        os.system('vgcreate () {}'.format(folder, disk))
                        print("VG created successfully")
                        partition_name = input("Enter the partiton name you want to give: ")
                        print("400M is here M means MB and just like this you can give 400G/T/M/K")
                        partition_size = input("Enter the partition size in this format - 400M or 20G: ")
                        os.system('lvcreate --size {} --name {}  {}'.format(partition_size, partition_name, folder))
                        os.system('lvdisplay {}'.format(folder, partition_name))
                        os.system('mkfs.ext4 /dev/{}/{}'.formate(folder, partition_name))
                        mount = ("Enter the folder name that you want to link with this partition: ")
                        os.mkdir(mount)
                        res = os.system('mount /dev/{}/{}  /{}'.format(folder, partition_name, mount))
                        if res == o:
                            print("Your drive of {} has been created successfully".format(partition_size))
                        else:
                            print("Some internal error occure please try again")
                    elif int(lvm) == 3:
                        partition_name = input("Enter the existing partiton name you want to increase: ")
                        partition_size = input("Enter the partition size in this format - 400M or 20G: ")
                        folder = input("enter the existing folder nameyou have created before partition: ")
                        os.system('lvextend --size {}  /dev{}/{}'.format(partition_size, folder, partition_name))
                        os.system('resize2fs  /dev{}/{}'.format(partition_size, folder, partition_name))
                        print("Existing drive extended successfully")
                    elif int(lvm) == 4:
                        newdisk = input("Enter the newly attached hard disk full name eg - /dev/sda: ")
                        newfolder = input("enter the folder name: ")
                        os.system('vgextend {} {}'.format(newfolder, newdisk))
                        print("new hard disk attach successfully")
                    elif int(lvm) == 5:
                        os.system('df -l')